config/urls.py
"""config URL Configuration

Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('pw/', include('pw.urls')),
]

hello/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('turma/', views.turma_view, name='turma')
]

pw/urls.py
from . import views
from django.urls import path


app_name = 'pw'

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('about/', views.about_view, name='about')
]

hello/models.py
from django.db import models

# Create your models here.

pw/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


def index_view(request):
    return HttpResponse('Hello world!')


def turma_view(request):
    return HttpResponse("Olá turma!")

pw/views.py
from django.shortcuts import render
from datetime import datetime
# Create your views here.

def index_view(request):

    linguagens = ['JS', 'Python']

    context = {
        'ano': datetime.now().year,
        'hora': datetime.now().hour,
        'linguagens': linguagens,
    }

    return render(request, 'pw/index.html', context)



def about_view(request):
    
    context = {
        'ano': datetime.now().year
    }
    return render(request, 'pw/about.html', context)

pw/templates/pw/about.html
{% extends "pw/layout.html" %}

{% block main %}

<p>Disciplina de LEI e LIG</p>

{% endblock main %}

pw/templates/pw/index.html
{% extends "pw/layout.html" %}

{% block main %}

    {% if hora < 12 %}
      <p>Bom dia!</p>
    {% else %}
      <p>Boa tarde!</p>
    {% endif %}
 
<p>Aplicações web em Django</p>  

<p>Linguagens</p>
<ul>
    {% for linguagem in linguagens %}
      <li> {{ linguagem }} </li>
    {% endfor %}
</ul>

{% load static %}
<img src="{% static 'pw/pw.png' %}" alt="">

{% endblock main %}

pw/templates/pw/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PW</title>
    <style>

        body {
            background-color: khaki;;
        }
    </style>
</head>

<body>
    <header>
        <h1>Programação Web</h1>

        <a href="{% url 'pw:index' %}">Index</a>
        <a href="{% url 'pw:about' %}">About</a>

    </header>
    <main>
       
        {% block main %}
          
        {% endblock main %}

    </main>

    <footer>
        <p>Universidade Lusófona, {{ ano }} </p>
    </footer>
</body>

</html>